Test CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -131,15 +131,10 @@ jobs:
 
             # Run migrations with error handling
             echo "🛠 Running migrations..."
-            if docker compose exec wsimpleapp php artisan migrate --force; then
-                echo "✅ Migrations success"
-            else
-                echo "❌ Migrations failed"
-                exit 1
-            fi
+            docker exec wsimpleapp php artisan migrate --force || { echo "Error: Migrations failed."; exit 1; }
 
             echo "Copying assets to S3..."
-            docker compose exec wsimpleapp bash <<'OUTER_EOF'
+            docker exec wsimpleapp bash <<'OUTER_EOF'
             # Konfigurasi
             ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
             SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
