Test CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,9 +14,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Create .env.production file
+      - name: Create .env.{{ vars.APP_NAME }} file
         run: |
-          cat > wsimpleapp.env <<EOF
+          cat > .env.${{ vars.APP_NAME }} <<EOF
           APP_NAME=${{ vars.APP_NAME }}
           APP_ENV=${{ vars.APP_ENV }}
           APP_KEY=${{ secrets.APP_KEY }}
@@ -63,19 +63,19 @@ jobs:
           chmod 600 ~/.ssh/id_ed25519
           ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
 
-      # - name: Upload .env.production to VPS
-      #   run: |
-      #     ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/id_ed25519 << 'EOF'
-      #       set -e
-      #       # Check if the target directory exists, and create it if not
-      #       echo "Checking if target directory exists..."
-      #       if [ ! -d "${{ vars.VPS_DOCKER_PATH }}" ]; then
-      #         echo "Target directory does not exist. Creating it..."
-      #         mkdir -p ${{ vars.VPS_DOCKER_PATH }} || { echo "Error: Failed to create target directory."; exit 1; }
-      #       fi
-      #     EOF
+      - name: Upload .env.{{ vars.APP_NAME }} to VPS
+        run: |
+          # ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/id_ed25519 << 'EOF'
+          #   set -e
+          #   # Check if the target directory exists, and create it if not
+          #   echo "Checking if target directory exists..."
+          #   if [ ! -d "${{ vars.VPS_DOCKER_PATH }}" ]; then
+          #     echo "Target directory does not exist. Creating it..."
+          #     mkdir -p ${{ vars.VPS_DOCKER_PATH }} || { echo "Error: Failed to create target directory."; exit 1; }
+          #   fi
+          # EOF
 
-      #     scp -i ~/.ssh/id_ed25519 .env.production ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.VPS_DOCKER_PATH }}/.env.production
+          scp -i ~/.ssh/id_ed25519 .env.{{ vars.APP_NAME }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/dev/.env.{{ vars.APP_NAME }}
 
       - name: Deploy via SSH
         run: |
@@ -105,7 +105,7 @@ jobs:
 
             # scp -i ~/.ssh/id_ed25519 .env.production ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.VPS_DOCKER_PATH }}/.env.production
             echo "✅ .env.production copied to Project."
-            # mv /home/dev/${{ vars.APP_NAME }}.env ${{ vars.VPS_DOCKER_PATH }}/.env.production
+            mv /home/dev/.env.${{ vars.APP_NAME }} ${{ vars.VPS_DOCKER_PATH }}/.env.production
 
             # Check if the .env.production file exists before copying
             echo "✅ Copying .env.production to .env"
