Test CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -85,6 +85,13 @@ jobs:
           # Navigate to the Docker project directory
           cd ${{ vars.VPS_DOCKER_PATH }}
 
+          # Check if the current directory is a Git repository
+          echo "📥 Checking if directory is a Git repository..."
+          if [ ! -d ".git" ]; then
+            echo "No Git repository found. Cloning repository..."
+            git clone git@github.com:letio-dev/wsimpleapp.git . || { echo "Error: Failed to clone repository."; exit 1; }
+          fi
+
           # Pull the latest changes from the repository
           echo "📥 Pulling latest code..."
           git pull origin main || { echo "Error: Failed to pull the latest code."; exit 1; }
