Test CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -130,8 +130,58 @@ jobs:
             docker compose up -d --build || { echo "Error: Failed to bring Docker services up."; exit 1; }
 
             # Run migrations with error handling
-            echo "🛠 Running migrations..."
-            docker compose exec wsimpleapp php artisan migrate --force
+            # echo "🛠 Running migrations..."
+            # docker compose exec wsimpleapp php artisan migrate --force || { echo "Error: Migrations failed."; exit 1; }
 
             echo "Copying assets to S3..."
+            docker compose exec wsimpleapp bash <<'OUTER_EOF'
+            # Konfigurasi
+            ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
+            SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
+            ENDPOINT="${{ vars.ENDPOINT }}"
+            BUCKET="${{ vars.BUCKET }}"
+            PREFIX="${{ vars.PREFIX }}"
+            SOURCE_DIR="/var/www/public/build"
+
+            # Cek awscli
+            if ! command -v aws &> /dev/null
+            then
+                echo "awscli not found. Installing awscli..."
+                apt update && apt install awscli -y
+            fi
+
+            # Export credentials sementara
+            export AWS_ACCESS_KEY_ID="$ACCESS_KEY"
+            export AWS_SECRET_ACCESS_KEY="$SECRET_KEY"
+
+            # Upload semua file
+            echo "Uploading files to S3..."
+            aws --endpoint-url="$ENDPOINT" s3 cp "$SOURCE_DIR" "s3://$BUCKET/$PREFIX/build/" --recursive --acl public-read
+
+            # Buat file CORS policy
+            echo "Creating CORS file..."
+            cat > /tmp/cors.json <<'INNER_EOF'
+            {
+              "CORSRules": [
+                {
+                  "AllowedHeaders": ["*"],
+                  "AllowedMethods": ["GET", "POST", "PUT", "DELETE", "HEAD"],
+                  "AllowedOrigins": [${{ vars.S3_CORS_ALLOW_ORIGINS }}],
+                  "ExposeHeaders": [],
+                  "MaxAgeSeconds": 3000
+                }
+              ]
+            }
+            INNER_EOF
+
+            # Set CORS ke bucket
+            echo "Setting CORS configuration..."
+            aws --endpoint-url="$ENDPOINT" s3api put-bucket-cors --bucket "$BUCKET" --cors-configuration file:///tmp/cors.json
+
+            # Bersihkan file sementara
+            rm -f /tmp/cors.json
+
+            echo "All done successfully!"
+            OUTER_EOF
+
           EOF
