Test CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -135,57 +135,57 @@ jobs:
 
             echo "Copying assets to S3..."
             docker exec wsimpleapp bash <<'OUTER_EOF'
-            # Konfigurasi
-            ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
-            SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
-            ENDPOINT="${{ vars.S3_ENDPOINT }}"
-            BUCKET="${{ vars.S3_BUCKET }}"
-            PREFIX="${{ vars.S3_PREFIX }}"
-            SOURCE_DIR="/var/www/public/build"
+              # Konfigurasi
+              ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
+              SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
+              ENDPOINT="${{ vars.S3_ENDPOINT }}"
+              BUCKET="${{ vars.S3_BUCKET }}"
+              PREFIX="${{ vars.S3_PREFIX }}"
+              SOURCE_DIR="/var/www/public/build"
 
-            # Cek awscli
-            if ! command -v aws &> /dev/null
-            then
-                echo "awscli not found. Installing awscli..."
-                apt update && apt install awscli -y
-            fi
+              # Cek awscli
+              if ! command -v aws &> /dev/null
+              then
+                  echo "awscli not found. Installing awscli..."
+                  apt update && apt install awscli -y
+              fi
 
-            # Export credentials sementara
-            export AWS_ACCESS_KEY_ID="$ACCESS_KEY"
-            export AWS_SECRET_ACCESS_KEY="$SECRET_KEY"
+              # Export credentials sementara
+              export AWS_ACCESS_KEY_ID="$ACCESS_KEY"
+              export AWS_SECRET_ACCESS_KEY="$SECRET_KEY"
 
-            # Kosongkan dulu folder tujuan
-            echo "Deleting old files in S3 bucket path ($BUCKET/$PREFIX/build)..."
-            aws --endpoint-url="$ENDPOINT" s3 rm "s3://$BUCKET/$PREFIX/build" --recursive
+              # Kosongkan dulu folder tujuan
+              echo "Deleting old files in S3 bucket path ($BUCKET/$PREFIX/build)..."
+              aws --endpoint-url="$ENDPOINT" s3 rm "s3://$BUCKET/$PREFIX/build" --recursive
 
-            # Upload semua file
-            echo "Uploading files to S3..."
-            aws --endpoint-url="$ENDPOINT" s3 cp "$SOURCE_DIR" "s3://$BUCKET/$PREFIX/build/" --recursive --acl public-read
+              # Upload semua file
+              echo "Uploading files to S3..."
+              aws --endpoint-url="$ENDPOINT" s3 cp "$SOURCE_DIR" "s3://$BUCKET/$PREFIX/build/" --recursive --acl public-read
 
-            # Buat file CORS policy
-            echo "Creating CORS file..."
-            cat > /tmp/cors.json <<'INNER_EOF'
-            {
-              "CORSRules": [
+              # Buat file CORS policy
+              echo "Creating CORS file..."
+              cat > /tmp/cors.json <<'INNER_EOF'
                 {
-                  "AllowedHeaders": ["*"],
-                  "AllowedMethods": ["GET", "POST", "PUT", "DELETE", "HEAD"],
-                  "AllowedOrigins": [${{ vars.S3_CORS_ALLOW_ORIGINS }}],
-                  "ExposeHeaders": [],
-                  "MaxAgeSeconds": 3000
+                  "CORSRules": [
+                    {
+                      "AllowedHeaders": ["*"],
+                      "AllowedMethods": ["GET", "POST", "PUT", "DELETE", "HEAD"],
+                      "AllowedOrigins": [${{ vars.S3_CORS_ALLOW_ORIGINS }}],
+                      "ExposeHeaders": [],
+                      "MaxAgeSeconds": 3000
+                    }
+                  ]
                 }
-              ]
-            }
-            INNER_EOF
+              INNER_EOF
 
-            # Set CORS ke bucket
-            echo "Setting CORS configuration..."
-            aws --endpoint-url="$ENDPOINT" s3api put-bucket-cors --bucket "$BUCKET" --cors-configuration file:///tmp/cors.json
+              # Set CORS ke bucket
+              echo "Setting CORS configuration..."
+              aws --endpoint-url="$ENDPOINT" s3api put-bucket-cors --bucket "$BUCKET" --cors-configuration file:///tmp/cors.json
 
-            # Bersihkan file sementara
-            rm -f /tmp/cors.json
+              # Bersihkan file sementara
+              rm -f /tmp/cors.json
 
-            echo "All done successfully!"
+              echo "All done successfully!"
             OUTER_EOF
 
             echo "✅ Finished deploying!"
