Test CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,6 +22,7 @@ jobs:
           APP_KEY=${{ secrets.APP_KEY }}
           APP_DEBUG=${{ vars.APP_DEBUG }}
           APP_URL=${{ vars.APP_URL }}
+          ASSET_URL=${{ vars.ASSET_URL }}
 
           APP_LOCALE=${{ vars.APP_LOCALE }}
           APP_FALLBACK_LOCALE=${{ vars.APP_FALLBACK_LOCALE }}
@@ -65,16 +66,6 @@ jobs:
 
       - name: Upload .env.production to VPS
         run: |
-          # ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/id_ed25519 << 'EOF'
-          #   set -e
-          #   # Check if the target directory exists, and create it if not
-          #   echo "Checking if target directory exists..."
-          #   if [ ! -d "${{ vars.VPS_DOCKER_PATH }}" ]; then
-          #     echo "Target directory does not exist. Creating it..."
-          #     mkdir -p ${{ vars.VPS_DOCKER_PATH }} || { echo "Error: Failed to create target directory."; exit 1; }
-          #   fi
-          # EOF
-
           scp -i ~/.ssh/id_ed25519 .env.production ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/dev/.env.${{ vars.APP_NAME }}
 
       - name: Deploy via SSH
@@ -141,5 +132,56 @@ jobs:
             # Run migrations with error handling
             echo "🛠 Running migrations..."
             docker compose exec wsimpleapp php artisan migrate --force || { echo "Error: Migrations failed."; exit 1; }
+
+            echo "Copying assets to S3..."
+            docker compose exec wsimpleapp bash <<'OUTER_EOF'
+            # Konfigurasi
+            ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
+            SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
+            ENDPOINT="${{ vars.ENDPOINT }}"
+            BUCKET="${{ vars.BUCKET }}"
+            PREFIX="${{ vars.PREFIX }}"
+            SOURCE_DIR="/var/www/public/build"
+
+            # Cek awscli
+            if ! command -v aws &> /dev/null
+            then
+                echo "awscli not found. Installing awscli..."
+                apt update && apt install awscli -y
+            fi
+
+            # Export credentials sementara
+            export AWS_ACCESS_KEY_ID="$ACCESS_KEY"
+            export AWS_SECRET_ACCESS_KEY="$SECRET_KEY"
+
+            # Upload semua file
+            echo "Uploading files to S3..."
+            aws --endpoint-url="$ENDPOINT" s3 cp "$SOURCE_DIR" "s3://$BUCKET/$PREFIX/build/" --recursive --acl public-read
+
+            # Buat file CORS policy
+            echo "Creating CORS file..."
+            cat > /tmp/cors.json <<'INNER_EOF'
+            {
+              "CORSRules": [
+                {
+                  "AllowedHeaders": ["*"],
+                  "AllowedMethods": ["GET", "POST", "PUT", "DELETE", "HEAD"],
+                  "AllowedOrigins": [${{ vars.S3_CORS_ALLOW_ORIGINS }}],
+                  "ExposeHeaders": [],
+                  "MaxAgeSeconds": 3000
+                }
+              ]
+            }
+            INNER_EOF
+
+            # Set CORS ke bucket
+            echo "Setting CORS configuration..."
+            aws --endpoint-url="$ENDPOINT" s3api put-bucket-cors --bucket "$BUCKET" --cors-configuration file:///tmp/cors.json
+
+            # Bersihkan file sementara
+            rm -f /tmp/cors.json
+
+            echo "All done successfully!"
+            OUTER_EOF
 
           EOF
